import "./globals.css";
import { Inter } from "next/font/google";
import IsAuth from "./PrivateRoute";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <IsAuth>{children}</IsAuth>
      </body>
    </html>
  );
}
